site_name: DaVinci Resolve 19 User Documentation
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    # - navigation.tabs #Optional if we want to change the navigation
    - navigation.sections
    - navigation.expand
    - toc.integrate
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

plugins:
  - search

markdown_extensions:
- admonition
- attr_list



copyright: Copyright &copy; 2025 Guri & Patrick
